name: Test

on:
  pull_request:
  push:
    branches: [master]
    tags: ['*']

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make deps
      - name: Start test database
        run: ./hack/postgresd.sh
      - name: Lint and test
        run: make all
